version: "3.9"

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"


services:

  nginx:
    image: nginx:1.21
    restart: unless-stopped
    logging: *logging
    volumes:
      - ./www:/var/www
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9090:80"


  php:
    build: .
    restart: unless-stopped
    logging: *logging
    healthcheck:
      test: ["CMD-SHELL", "curl http://nginx || grep 'works'"]
      interval: 5s
      timeout: 5s
      retries: 5

